# Generated by Django 5.1.6 on 2025-03-04 18:46

import miweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0002_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to=miweb.models.upload_to_media, verbose_name='Imagen de Portada'),
        ),
    ]
